# Run tests on all supported platforms, compilers and C++ dialects. This is not part of the full CI workflow, since
# these tests are vastly more expensive.
# MacOS tests are insanely slow, and each minute of testing costs 10x what the Linux tests cost.
# Windows tests are slow and each minute of testing costs 2x what the Linux tests cost.
name: Full cross-platform testing

on:
  # This workflow is run manually from the Actions tab.
  workflow_dispatch:
  schedule:
  # Every Friday at 08:43 UTC (04:43 Eastern)
  - cron: '43 04 * * 5'

jobs:
  test_ubuntu-current:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        cc: [clang-8, gcc-8, gcc-9]
        cpp-dialect: [c++14, c++17]
        os: [ubuntu-18.04, ubuntu-20.04]
      fail-fast: false

    env:
      bazel-user-root: ~/.cache/bazel/_bazel_${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hydrate Bazel cache
        uses: actions/cache@v2
        env:
          cache-name: bazel-build-cache

        with:
          path: ${{ env.bazel-user-root }}
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}-${{ github.sha }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}
            ${{ env.cache-name }}-${{ matrix.os }}

      - name: Test
        run: bazel --output_user_root=${{ env.bazel-user-root }} test --cxxopt='-std=${{ matrix.cpp-dialect}}' //...
        env:
          CC: ${{ matrix.cc }}

  test_ubuntu-bleeding-edge:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        cc: [clang-10, clang-11, gcc-10]
        cpp-dialect: [c++20]
        os: [ubuntu-20.04]
      fail-fast: false

    env:
      bazel-user-root: ~/.cache/bazel/_bazel_${{ github.repository_owner }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hydrate Bazel cache
        uses: actions/cache@v2
        env:
          cache-name: bazel-build-cache

        with:
          path: ${{ env.bazel-user-root }}
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}-${{ github.sha }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}
            ${{ env.cache-name }}-${{ matrix.os }}

      - name: Test
        run: bazel --output_user_root=${{ env.bazel-user-root }} test --cxxopt='-std=${{ matrix.cpp-dialect}}' //...
        env:
          CC: ${{ matrix.cc }}

  test_ubuntu-oldest-supported:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        cc: [clang-6.0, gcc-5]
        cpp-dialect: [c++14]
        os: [ubuntu-16.04]
      fail-fast: false

    env:
      bazel-user-root: ~/.cache/bazel/_bazel_${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hydrate Bazel cache
        uses: actions/cache@v2
        env:
          cache-name: bazel-build-cache
          CC: ${{ matrix.cc }}

        with:
          path: ${{ env.bazel-user-root }}
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}-${{ github.sha }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}
            ${{ env.cache-name }}-${{ matrix.os }}

      - name: Test
        run: bazel --output_user_root=${{ env.bazel-user-root }} test --cxxopt='-std=${{ matrix.cpp-dialect}}' //...
        env:
          CC: ${{ matrix.cc }}

  test_macos-latest:
    runs-on: macos-latest

    strategy:
      matrix:
        cpp-dialect: [c++17]
      fail-fast: false

    env:
      bazel-user-root: ~/.cache/bazel/_bazel_${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hydrate Bazel cache
        uses: actions/cache@v2
        env:
          cache-name: bazel-build-cache

        with:
          path: ${{ env.bazel-user-root }}
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}-${{ github.sha }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}
            ${{ env.cache-name }}-${{ matrix.os }}
        
      - name: Test
        run: bazel --output_user_root=${{ env.bazel-user-root }} test --cxxopt='-std=${{ matrix.cpp-dialect}}' //...

  test_windows-latest:
    runs-on: windows-latest

    strategy:
      matrix:
        cpp-dialect: [c++14, c++17]
      fail-fast: false

    env:
      bazel-user-root: ${GITHUB_WORKSPACE}\_bazel_${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hydrate Bazel cache
        uses: actions/cache@v2
        env:
          cache-name: bazel-build-cache

        with:
          path: ${{ env.bazel-user-root }}
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}-${{ github.sha }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}-${{ matrix.cpp-dialect }}
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cc }}
            ${{ env.cache-name }}-${{ matrix.os }}

      - name: Test
        run: bazel.exe --output_user_root=${{ env.bazel-user-root }} test --cxxopt='/std:${{ matrix.cpp-dialect}}' //...
